language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
      env:
         - COMPILER="CC=gcc-5 && CXX=g++-5"
      before_install: eval "${COMPILER}"
      script: make travis
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      env:
         - COMPILER="CC=gcc-7 && CXX=g++-7"
      before_install: eval "${COMPILER}"
      script: make travis
    - os: linux
      compiler: clang
    - os: windows
      install: choco install mingw
      script: mingw32-make travis
    - os: windows
      install: choco install mingw --version 4.9.3 --force
      script: mingw32-make travis
    - os: windows
      script: 
        - mkdir build && cd build
        - cmake .. 
        - cmake --build . 